name: Demo on macos arm64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-15]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install ninja-build, bazel and local dependencies (macos)
      if: contains(matrix.os, 'macos')
      run: |
        brew install ninja
        brew install bazelisk
    - name: Install cmake with pipx (All)
      run: |
        pipx install cmake
    - name: demo-project1 (bazel macos)
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        bazel run //demo:demo1
        
    - name: compile manually c++17
      run: |
        echo "compiling examples/modlog1"
        c++ examples/modlog1/main-cpp17.cpp --std=c++17 -I./include/ -o example_cpp17
        echo "running examples/modlog1"
        ./example_cpp17
        cd examples/modlog1 && ls -la && make

    - name: compile manually c++20
      run: |
        echo "compiling examples/modlog1"
        c++ examples/modlog1/main-cpp17.cpp --std=c++20 -I./include/ -o example_cpp20
        echo "running examples/modlog1"
        ./example_cpp20
        cd examples/modlog1 && ls -la && make
        
