name: Demo on ubuntu arm
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Print Hello World
        run: 'echo "Hello World"'
      - name: Install ninja-build, bazelisk and local dependencies (Ubuntu)
        run: |
          sudo apt-get install ninja-build -y
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

          export NVM_DIR="$HOME/.nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

          . "$NVM_DIR/nvm.sh"
          nvm install --lts
          nvm use --lts

          # Now install bazelisk globally
          npm install -g @bazel/bazelisk

          # Optionally verify everything is working
          node --version
          bazelisk version

          echo "OK"

          bash -i -c "nvm install --lts"
          bash -i -c "sudo npm install -g @bazel/bazelisk"
          bash -i -c "sudo apt install clang-19 clang-tools-19 libc++-19-dev"

