name: Demo on ubuntu arm
on:
  push:
    branches:
      - main

jobs:
  demo_arm:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Print Hello World
        run: 'echo "Hello World"'
      - name: Install ninja-build, bazelisk and local dependencies (Ubuntu)
        run: |
          sudo apt-get install ninja-build -y
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

          export NVM_DIR="$HOME/.nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

          . "$NVM_DIR/nvm.sh"
          nvm install --lts
          nvm use --lts
          npm install -g @bazel/bazelisk
          node --version
          bazelisk version
          sudo apt install clang-19 clang-tools-19 libc++-19-dev

      - name: demo-project1 (bazel ubuntu)
        run: |
          bazel run //demo:demo1
