name: Demo on ubuntu arm (32)
on:
  push:
    branches:
      - main

jobs:
  run_on_arch:
    runs-on: ubuntu-22.04
    name: Build on ARM Architecture
    steps:
      - uses: actions/checkout@v4

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands on ARM
        with:
          arch: armv7
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

